[package]
name = "rename-me"
version = "0.0.0-git"
authors = [
	"Mavity The Madity",
]
edition = "2024"
rust-version = "1.99.0"
description = "Foo bar baz"
homepage = "https://github.com/EpicVon2468/rename-me/"
repository = "https://github.com/EpicVon2468/rename-me/"
license = "MIT OR Apache-2.0"
exclude = [
	".github/",
]

[features]
llvm-shared = [
	"inkwell/llvm22-1-force-dynamic",
]
llvm-static = [
	"inkwell/llvm22-1-force-static",
]

[[bin]]
name = "renamec"
path = "src/main.rs"
test = true
doctest = true
bench = true
doc = true
proc-macro = false
harness = true

[package.metadata.dist]
dist = true
# https://github.com/axodotdev/cargo-dist/issues/745
#features = [
#]

[dependencies.anyhow]
version = ">=1.0.104, <2"

[dependencies.inkwell]
version = ">=0.9.0, <1"
features = [
	# Inkwell would just duplicate the linking.
	"no-libffi-linking",
	"llvm22-1",
	"nightly",
	"target-x86",
	"target-aarch64",
	"target-powerpc",
	"target-riscv",
	"target-loongarch",
]
default-features = false

[dependencies.thiserror]
version = ">=2.0.19, <3"

[dependencies.derive_more]
version = ">=2.1.1, <3"
features = [
	"constructor",
	"display",
]

[dependencies.shell-words]
version = ">=1.1.1, <2"

[build-dependencies.roff]
version = ">=1.1.1, <2"

[build-dependencies.cc]
version = ">=1.4.0, <2"

[build-dependencies.shell-words]
version = ">=1.1.1, <2"

[patch.crates-io]
inkwell = {
	git = "https://github.com/EpicVon2468/inkwell",
}
llvm-sys = {
	path = "vendored/llvm-sys",
}

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "fat"